name: Frontend app build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: FRONTEND/package-lock.json

      - name: Install dependencies
        working-directory: ./FRONTEND
        run: npm ci

      - name: Build application
        working-directory: ./FRONTEND
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Frontend-app
          path: FRONTEND/dist
